#!/usr/bin/env bash

function setup()
{
    echo '>>> Setting up analyser...'

    # Setup environment
    source .env
    export DOCKER_IMAGE_PHP \
        DOCKER_NETWORK
}

function analyse()
{
    echo '>>> Analysing...'

    docker run --rm \
        -v $PWD/:/var/www/html \
        --network $DOCKER_NETWORK \
        $DOCKER_IMAGE_PHP \
        ./vendor/bin/phpstan analyse \
            -c ./config/phpstan.neon \
            --error-format prettyJson > logs/analyse
}

setup
analyse
