#!/usr/bin/env bash

docker run --interactive --rm \
    --name composer \
    --volume $PWD:/app \
    composer:1.10 \
    composer $@

docker run -it --rm \
    --name composer \
    --volume $PWD:/app \
    composer:1.10 \
    composer dump-autoload -o
ompoc
