#!/usr/bin/env bash

function setup()
{
    echo '>>> Setting up style checker...'

    # Setup environment
    source .env
    export DOCKER_IMAGE_PHP \
        DOCKER_NETWORK
}

function styleCheck()
{
    docker run --rm \
        -v $PWD/:/var/www/html \
        --network $DOCKER_NETWORK \
        $DOCKER_IMAGE_PHP \
        ./vendor/bin/phpcbf /var/www/html/src \
            --standard=PSR2
}

setup
styleCheck
