#!/usr/bin/env bash

function setup()
{
    echo '>>> Setting up...'

    # Setup environment
    source .env
    export DOCKER_IMAGE_PHP \
        DOCKER_NETWORK
}

function test()
{
    echo '>>> Testing...'

    docker run --rm \
        -v $PWD/:/var/www/html \
        --network $DOCKER_NETWORK \
        $DOCKER_IMAGE_PHP \
        ./vendor/bin/phpunit ./test --testdox
}

setup
test
